language: node_js

deploy:
  - provider: elasticbeanstalk
    skip_cleanup: true
    access_key_id: AKIAIS4ABNSYS5HWUFTA
    secret_access_key:
      secure: fUiJ/1ux1sVFj8jMIyyygv8XXQr/0RuyOXlSM2Pak4FpXSb4YLU024GSV4nE1om2ev2lMOPsJC2fGq5nOD/+UxlXjq4RGtaJfPNFWnrpSlIO5CV7rXtcnHTx5OOcu5wq1NBUVsSMC/62CeJmULksBSgUopnKPuSsxA/khRgOR+i3cBM8vbfQpOO565imUDa51OqGL7EcRBBOp3bHxYks+PSknsT8r7PZGWWgpVxQc8GdiMNEusm6Wbh2tfcNB8XWlriLgjyICpM/fBwZaz0jpFWfeuUJELcXBYzrqFtMrXSJeqHrKQKB7MPgUCouRJ6IHYuJe/13i3o9l4DT83X5GUJUeG3mNShtTn8VskJa7ejdkOEzm9gxVXcpMLQo7tCkiIMBUmTTVxsWIs/y1vm11MRsVHS3EGS/GMwfmpWyj8UuLwB/lvdImoBxlkn1RosgfczYAea6AG3qZFTBxxudsZQZeDbbxI49yrkG7tCqayhNPHsCkLTsqvfaffMJ0FGJcr4/Kb+/d1r3TL9sjrQw0AO5jfe4ra11g0g1F6iIePSBM4mw5AlYbabckzur+KFvedgQ4i9NwMVBkWMmckS3pMBJ3A11RcbHZZQG7YPm0TubiLLlkbYQUPfNQFCn03em6rtv4RJf807+jUolnOx21HuRlBr46d9kUmFm7XryCpE=
    region: us-east-1
    app: Hyperaudio API
    env: hyperaudio-alpha
    bucket_name: elasticbeanstalk-us-east-1-585082712647
    on:
      branch: develop
#  - provider: elasticbeanstalk
#    access_key_id: AKIAIS4ABNSYS5HWUFTA
#    secret_access_key:
#      secure: fUiJ/1ux1sVFj8jMIyyygv8XXQr/0RuyOXlSM2Pak4FpXSb4YLU024GSV4nE1om2ev2lMOPsJC2fGq5nOD/+UxlXjq4RGtaJfPNFWnrpSlIO5CV7rXtcnHTx5OOcu5wq1NBUVsSMC/62CeJmULksBSgUopnKPuSsxA/khRgOR+i3cBM8vbfQpOO565imUDa51OqGL7EcRBBOp3bHxYks+PSknsT8r7PZGWWgpVxQc8GdiMNEusm6Wbh2tfcNB8XWlriLgjyICpM/fBwZaz0jpFWfeuUJELcXBYzrqFtMrXSJeqHrKQKB7MPgUCouRJ6IHYuJe/13i3o9l4DT83X5GUJUeG3mNShtTn8VskJa7ejdkOEzm9gxVXcpMLQo7tCkiIMBUmTTVxsWIs/y1vm11MRsVHS3EGS/GMwfmpWyj8UuLwB/lvdImoBxlkn1RosgfczYAea6AG3qZFTBxxudsZQZeDbbxI49yrkG7tCqayhNPHsCkLTsqvfaffMJ0FGJcr4/Kb+/d1r3TL9sjrQw0AO5jfe4ra11g0g1F6iIePSBM4mw5AlYbabckzur+KFvedgQ4i9NwMVBkWMmckS3pMBJ3A11RcbHZZQG7YPm0TubiLLlkbYQUPfNQFCn03em6rtv4RJf807+jUolnOx21HuRlBr46d9kUmFm7XryCpE=
#    region: us-east-1
#    app: Hyperaudio API
#    env: hyperaudio-beta
#    bucket_name: elasticbeanstalk-us-east-1-585082712647
#    on:
#      branch: master

notifications:
  slack:
    secure: ETZzUJd155O+7FTqEyqmMy7jOMoAbaUTtbetkXBA9kWsh89XKMlC2WiE3pg0M8cfl5ANEn/rArXSbhkawCJXY6EodVTXv8qthBX7H7QMCcEZIRKkbifpRj+H4VdZSA61iXBXNhLgWfTPIe1q8cc+sqVlsir0DSsUv6cAQsYFTzz7yZpHDyXsRknKyRZQ/udzI6fOayeAWfAp/pPg6LHfEffbyCdWK/xyhfMTTN/ZMQfV5RWlRAvrY6LTj7PVlOdVItNpcpliXooJR3MQ7/SpMEcCfqhjpqV/7+MAxJ9ZDOEkUYJYabSrRTAp277plfa6+FJBjYPUPl5ok5Y4P7ZhHQtowDN/YMK3H8LTaA4s94jcyDpjNLNzNuvmUFl49KM1gbUYau1O8eXrcFvQ1hUFNMP4Ds6sMwYZR6IcM/HLZCbGg1o6XWTJoMBCShqKxwUeUGIWkQJ2FHdUPt0dSzhDMNcxWb1xhmexRlH3nBRlZnVa7CQqIUYICs85qZ8J35KEfiXndJzxNACclL50W3KpSckGtSKQrLWBimCGAkzVaf5zzjJGrv7XHQRn+5v/cZ9a9lTcUhsHWiscgKz9FD6xVn6eRL6disGsgYVwxNMlmGDTGqoSRj/Poay+Yesm3zJ/hRKcSaZiG8HESZ0cYaQ64SAnkxnB/ifO7RGpR081LoM=
  irc: chat.freenode.net#hyperaudio
